version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.11

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-packages-{{ .Branch }}
          - yarn-packages-master
          - yarn-packages-

      - run:
          name: Install Node dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_moduels
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Deploy development branch to master
          command: |
            if [ "${CIRCLE_BRANCH}" = "${DEPLOY_BRANCH}" ]; then
              chmod +x deploy.sh
              ./deploy.sh
            fi
